### PR TITLE
Create gif

### PR DESCRIPTION
**Pull request by DuyenPTM**

### CODE REVIEW

**Comment by DuyenPTM** [comment]
xxZXZXZ

**Comment by DuyenPTM** [comment]
xdsds

**Comment by DuyenPTM** [comment]
sdfsdf

**Comment by DuyenPTM** [comment]
adfsdfdsf

**Comment by DuyenPTM** [comment]
cccccc

**Comment by DuyenPTM** [comment]
gvdfgsdfg

**Comment by DuyenPTM** [comment]
dfsdfsdf

**Comment by tungcaontq** [comment]
aaa

**Pull request merged**
